# Generated by Django 4.1.5 on 2023-02-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
