# Generated by Django 4.1.5 on 2023-01-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture')),
                ('teamname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
